// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMTSa_QV5QiDO3C79OmYUjH6Txlo3f6PQ',
    appId: '1:109260150258:web:dafbb37832663c2a8f076b',
    messagingSenderId: '109260150258',
    projectId: 'scholar-chat-app-c41b3',
    authDomain: 'scholar-chat-app-c41b3.firebaseapp.com',
    storageBucket: 'scholar-chat-app-c41b3.appspot.com',
    measurementId: 'G-5R08D2Z4MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2BU5LgGSzJOBnit0l1lVHKMgTdTmuBBE',
    appId: '1:109260150258:android:79641eb515b7efc48f076b',
    messagingSenderId: '109260150258',
    projectId: 'scholar-chat-app-c41b3',
    storageBucket: 'scholar-chat-app-c41b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzujuOi_2k5Wzd94VScicCDVM5Is2qX0o',
    appId: '1:109260150258:ios:a39ba6d1a44fca078f076b',
    messagingSenderId: '109260150258',
    projectId: 'scholar-chat-app-c41b3',
    storageBucket: 'scholar-chat-app-c41b3.appspot.com',
    iosClientId: '109260150258-5uuouqgvrevo9b13m8bnjafomnjsmkem.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzujuOi_2k5Wzd94VScicCDVM5Is2qX0o',
    appId: '1:109260150258:ios:36f83aa220a0476a8f076b',
    messagingSenderId: '109260150258',
    projectId: 'scholar-chat-app-c41b3',
    storageBucket: 'scholar-chat-app-c41b3.appspot.com',
    iosClientId: '109260150258-8kf4tc3dfdq5kk7014oggoh4cnl1kgvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
